var products = [ 
    { name: 'Mix para Sopa (250g)', amount: 0, url: '../images/shops/verduritas.jpeg', type: 'veggie' },
    { name: 'Mix Verduras para Wok (250g)', amount: 0, url: '../images/shops/wok.jpeg', type: 'veggie' },
    { name: 'Acelga (Paq)', amount: 0, url: '../images/shops/acelga.jpg', type: 'veggie' },
    { name: 'Achicoria (500g)', amount: 0, url: '../images/shops/achicoria.jpg', type: 'veggie' },
    { name: 'Aji Vinagre (500g)', amount: 0, url: '../images/shops/ajivinagre.jpg', type: 'veggie' },
    { name: 'Ajo (x3)', amount: 0, url: '../images/shops/ajo.jpg', type: 'veggie' },
    { name: 'Albahaca (x2)', amount: 0, url: '../images/shops/albahaca.jpg', type: 'veggie' },
    { name: 'Anco (kg)', amount: 0, url: '../images/shops/anco.jpg', type: 'veggie' },
    { name: 'Apio (kg)', amount: 0, url: '../images/shops/apio.jpg', type: 'veggie' },
    { name: 'Banana (kg)', amount: 0, url: '../images/shops/banana.jpeg', type: 'fruit', price: 55 },
    { name: 'Batata (kg)', amount: 0, url: '../images/shops/batata.jpg', type: 'veggie' },
    { name: 'Boniato (kg)', amount: 0, url: '../images/shops/boniato.jpg', type: 'veggie' },
    { name: 'Brocoli (kg)', amount: 0, url: '../images/shops/brocoli.jpg', type: 'veggie' },
    { name: 'Berenjena (kg)', amount: 0, url: '../images/shops/berenjena.jpg', type: 'veggie' },
    { name: 'Caboutie (kg)', amount: 0, url: '../images/shops/caboutie.jpg', type: 'veggie' },
    { name: 'Cebolla (kg)', amount: 0, url: '../images/shops/cebolla.jpg', type: 'veggie' },
    { name: 'Cebolla Morada (kg)', amount: 0, url: '../images/shops/cebollamorada.jpg', type: 'veggie' },
    { name: 'Chaucha (kg)', amount: 0, url: '../images/shops/chaucha.jpg', type: 'veggie' },
    { name: 'Cilantro (kg)', amount: 0, url: '../images/shops/cilantro.jpg', type: 'veggie' },
    { name: 'Ciruela (kg)', amount: 0, url: '../images/shops/ciruela.jpg', type: 'fruit', price: 70 },
    { name: 'Choclo x 2', amount: 0, url: '../images/shops/choclo.jpg', type: 'veggie' },
    { name: 'Coliflor (uni)', amount: 0, url: '../images/shops/coliflor.jpg', type: 'veggie' },
    { name: 'Durazno (kg)', amount: 0, url: '../images/shops/durazno.jpg', type: 'fruit', price: 70 },
    { name: 'Espinaca (400g)', amount: 0, url: '../images/shops/espinaca.jpg', type: 'veggie' },
    { name: 'Hinojo (Uni)', amount: 0, url: '../images/shops/hinojo.jpg', type: 'veggie' },
    { name: 'Kale Morado (400g)', amount: 0, url: '../images/shops/kalemorado.jpg', type: 'veggie' },
    { name: 'Kale (400g)', amount: 0, url: '../images/shops/kale.jpg', type: 'veggie' },
    { name: 'Kiwi (kg)', amount: 0, url: '../images/shops/kiwi.jpg', type: 'fruit', price: 70 },
    { name: 'Lechuga (500g)', amount: 0, url: '../images/shops/lechugacrespa.jpg', type: 'veggie' },
    { name: 'Lechuga Mantecosa (1/2kg)', amount: 0, url: '../images/shops/lechugacrespa.jpg', type: 'veggie' },
    { name: 'Lima (1/2 kg)', amount: 0, url: '../images/shops/lima.jpg', type: 'veggie' },
    { name: 'Limon (kg)', amount: 0, url: '../images/shops/limon.jpg', type: 'fruit', price: 60 },
    { name: 'Melon (kg)', amount: 0, url: '../images/shops/melon.jpg', type: 'fruit', price: 80 },
    { name: 'Mango (kg)', amount: 0, url: '../images/shops/mango.jpg', type: 'fruit', price: 80 },
    { name: 'Manzana Roja (kg)', amount: 0, url: '../images/shops/manzana.jpg', type: 'fruit', price: 60 },
    { name: '2Kg Manzana Roja', amount: 0, url: '../images/shops/manzana.jpg', type: 'fruit', price: 100 },
    { name: 'Manzana Verde (kg)', amount: 0, url: '../images/shops/manzanaverde.jpg', type: 'fruit', price: 80 },
    { name: 'Mandarina (kg)', amount: 0, url: '../images/shops/mandarina.jpg', type: 'fruit', price: 65 },
    { name: 'Maracuya (kg)', amount: 0, url: '../images/shops/maracuya.jpg', type: 'fruit', price: 100 },
    { name: 'Morron Verde(kg)', amount: 0, url: '../images/shops/morron.jpg', type: 'veggie' },
    { name: 'Morron Rojo(kg)', amount: 0, url: '../images/shops/morronrojo.jpg', type: 'veggie' },
    { name: 'Nabo (paq)', amount: 0, url: '../images/shops/nabo.jpg', type: 'veggie' },
    { name: 'Naranja (kg)', amount: 0, url: '../images/shops/naranja.jpg', type: 'fruit', price: 55 },
    { name: 'Pack Choi (kg)', amount: 0, url: '../images/shops/packchoi.jpg', type: 'veggie' },
    { name: 'Palta (500g)', amount: 0, url: '../images/shops/palta.jpg', type: 'fruit', price: 70 },
    { name: 'Papa (kg)', amount: 0, url: '../images/shops/papa.jpg', type: 'veggie' },
    { name: 'Papa Colorada (kg)', amount: 0, url: '../images/shops/papacolorada.jpg', type: 'veggie' },
    { name: 'Pomelo Rosado (kg)', amount: 0, url: '../images/shops/pomelo.jpg', type: 'fruit', price: 70 },
    { name: 'Pelon (kg)', amount: 0, url: '../images/shops/pelon.jpg', type: 'fruit', price: 75 },
    { name: 'Pepino (kg)', amount: 0, url: '../images/shops/pepino.jpg', type: 'veggie' },
    { name: 'Pera (kg)', amount: 0, url: '../images/shops/pera.jpeg', type: 'fruit', price: 70 },
    { name: 'Perejil (400g)', amount: 0, url: '../images/shops/perejil.jpg', type: 'veggie' },
    { name: 'Puerro (PAQ)', amount: 0, url: '../images/shops/puerro.jpg', type: 'veggie' },
    { name: 'Rabanito (500g)', amount: 0, url: '../images/shops/rabanito.jpg', type: 'veggie' },
    { name: 'Radicheta (500g)', amount: 0, url: '../images/shops/radicheta.jpg', type: 'veggie' },
    { name: 'Repollo (kg)', amount: 0, url: '../images/shops/repollo.jpg', type: 'veggie' },
    { name: 'Repollito de Brusela (1/2kg)', amount: 0, url: '../images/shops/repollitobrusela.jpg', type: 'veggie', price: 75 },
    { name: 'Remolacha (PAQ)', amount: 0, url: '../images/shops/remolacha.jpg', type: 'veggie' },
    { name: 'Rucula (500g)', amount: 0, url: '../images/shops/rucula.jpg', type: 'veggie' },
    { name: 'Sandia (kg)', amount: 0, url: '../images/shops/watermelon.jpg', type: 'fruit', price: 40 },
    { name: 'Tomate (kg)', amount: 0, url: '../images/shops/tomate.jpg', type: 'veggie' },
    { name: 'Toronja (uni)', amount: 0, url: '../images/shops/toronja.jpg', type: 'fruit', price: 50 },
    { name: 'Tomate Cherry (500g)', amount: 0, url: '../images/shops/tomatecherry.jpg', type: 'veggie' },
    { name: 'Uva (500g)', amount: 0, url: '../images/shops/uva.jpg', type: 'fruit', price: 50 },
    { name: 'Verdeo (500g)', amount: 0, url: '../images/shops/verdeo.jpg', type: 'veggie' },
    { name: 'Zanahoria (PAQ)', amount: 0, url: '../images/shops/zanahoria.jpg', type: 'veggie' },
    { name: 'Zapallito (kg)', amount: 0, url: '../images/shops/zapallitos.jpg', type: 'veggie' },
    { name: 'Zuchinni (kg)', amount: 0, url: '../images/shops/zuchinni.jpg', type: 'veggie' },
    { name: 'Budin banana y frutos rojos', amount: 0, url: '../images/shops/budinbananafrutosrojos.jpg', type: 'meal', price: 90 },
    { name: 'Budin banana y pera', amount: 0, url: '../images/shops/budinbananapera.jpg', type: 'meal', price: 90 },
    { name: 'Budin cacao amargo y frutos secos', amount: 0, url: '../images/shops/cacaoamargo.jpg', type: 'meal', price: 90 },
    { name: 'Tarta de verduras y harina integral (Porc)', amount: 0, url: '../images/shops/tartaintegral.jpg', type: 'meal', price: 100 },
    { name: 'Jengibre (100g)', amount: 0, url: '../images/shops/jengibre.jpg', type: 'meal', price: 30 },
    { name: 'Cúrcuma (100g)', amount: 0, url: '../images/shops/curcuma.jpeg', type: 'meal', price: 30 },
    { name: 'Champiñon (100g)', amount: 0, url: '../images/shops/champi.jpg', type: 'meal', price: 45 },
    { name: 'Portobello (100g)', amount: 0, url: '../images/shops/portobello.jpg', type: 'meal', price: 45 },
    { name: 'Shitake (100g)', amount: 0, url: '../images/shops/shitake.jpg', type: 'meal', price: 60 },
    { name: 'Gírgolas (100g)', amount: 0, url: '../images/shops/girgolas.jpg', type: 'meal', price: 60 },
    { name: 'Queso Gouda (100g)', amount: 0, url: '../images/shops/queso.jpeg', type: 'meal', price: 55 },
    { name: 'Nueces de Catamarca (500g)', amount: 0, url: '../images/shops/nueces.jpg', type: 'meal', price: 200 },
    { name: 'Mani pelado (500g)', amount: 0, url: '../images/shops/mani.jpg', type: 'meal', price: 200 },
    { name: 'Mix Frutos secos (500g)', amount: 0, url: '../images/shops/mixeco.jpg', type: 'meal', price: 200 },
    { name: 'Vino Biodinámico (750ml)', amount: 0, url: '../images/shops/vino.jpg', type: 'meal', price: 180 },
    { name: 'Tomate Triturado (1L)', amount: 0, url: '../images/shops/tomatetriturado.jpg', type: 'meal', price: 100 },
    { name: 'Chucrut (400 cm2)', amount: 0, url: '../images/shops/chucrut.jpg', type: 'meal', price: 100 },
    { name: 'Garbanzos (500g)', amount: 0, url: '../images/shops/garbanzo.jpg', type: 'meal', price: 55 },
    { name: 'Mijo (500g)', amount: 0, url: '../images/shops/mijo.jpg', type: 'meal', price: 55 },
    { name: 'Lentejas (500g)', amount: 0, url: '../images/shops/lenteja.jpg', type: 'meal', price: 55 },
    { name: 'Poroto Mung (500g)', amount: 0, url: '../images/shops/porotomung.jpg', type: 'meal', price: 55 },
    { name: 'Soja (500g)', amount: 0, url: '../images/shops/soja.jpg', type: 'meal', price: 55 },
    { name: 'Trigo candeal (500g)', amount: 0, url: '../images/shops/trigo.jpg', type: 'meal', price: 55 },
    { name: 'Poroto Colorado (500g)', amount: 0, url: '../images/shops/porotocolorado.jpg', type: 'meal', price: 55 },
    { name: 'Poroto Negro (500g)', amount: 0, url: '../images/shops/porotonegro.jpg', type: 'meal', price: 55 },
    { name: 'Avena arrollada (500g)', amount: 0, url: '../images/shops/avena.jpg', type: 'meal', price: 55 },
    { name: 'Azucar Mascabo (1kg)', amount: 0, url: '../images/shops/azucarmascabo.jpg', type: 'meal', price: 200 },
    { name: 'Fideos integrales "Campo Claro" (500g)', amount: 0, url: '../images/shops/fideointegral.jpg', type: 'meal', price: 130 },
    { name: 'Arroz Yamaní Integral "ORYZA" (1Kg)', amount: 0, url: '../images/shops/arrozyamani.jpg', type: 'meal', price: 180 },
    { name: 'Arroz integral Doble Carolina "ORYZA" (500g)', amount: 0, url: '../images/shops/arrozlargointegral.jpg', type: 'meal', price: 90 },
    { name: 'Granola (500g)', amount: 0, url: '../images/shops/granolaintegral.jpg', type: 'meal', price: 200 },
    { name: 'Azucar rubia orgánica "Schatzi" (500g)', amount: 0, url: '../images/shops/azucarrubia.jpg', type: 'meal', price: 65 },
    { name: 'Polenta "Del Campo" (500g)', amount: 0, url: '../images/shops/polenta.jpeg', type: 'meal', price: 60 },
    { name: 'Queso crema "La Choza" (175grs)', amount: 0, url: '../images/shops/quesocrema.jpeg', type: 'meal', price: 85 },
    { name: 'Yogurt Descremado de Mango y Maracuyá "La Choza" (1Lt)', amount: 0, url: '../images/shops/mangogrande.jpeg', type: 'meal', price: 160 },
    { name: 'Yogurt Entero de Vainilla "La Choza" (1Lt)', amount: 0, url: '../images/shops/vainillagrande.jpeg', type: 'meal', price: 185 },
    { name: 'Yogurt Entero de Mora "La Choza" (1Lt)', amount: 0, url: '../images/shops/moragrande.jpeg', type: 'meal', price: 185 },
    { name: 'Yogurt Entero de Frutilla "La Choza" (1Lt)', amount: 0, url: '../images/shops/frutillagrande.jpeg', type: 'meal', price: 185 },
    { name: 'Yogurt Entero de Durazno "La Choza" (1Lt)', amount: 0, url: '../images/shops/duraznogrande.jpeg', type: 'meal', price: 185 },
    { name: 'Yogurt Natural Descremado "La Choza" (175g)', amount: 0, url: '../images/shops/naturalchico.jpeg', type: 'meal', price: 50 },
    { name: 'Yogurt Entero de Mora "La Choza" (175g)', amount: 0, url: '../images/shops/morachico.jpeg', type: 'meal', price: 60 },
    { name: 'Yogurt Entero de Frutilla "La Choza" (175g)', amount: 0, url: '../images/shops/frutillachico.jpeg', type: 'meal', price: 60 },
    { name: 'Yogurt Descremado de Miel "La Choza" (175g)', amount: 0, url: '../images/shops/mielchico.jpeg', type: 'meal', price: 60 },
    { name: 'Raviolones orgánicos integrales de Calabaza y Queso "Dilaupé" (10 u)', amount: 0, url: '../images/shops/raviolesintegrales.jpg', type: 'meal', price: 180 },
    { name: 'Ravioles orgánicos integrales de Espinaca y Ricota "Dilaupé" (Plancha)', amount: 0, url: '../images/shops/raviolesintegrales.jpg', type: 'meal', price: 110 },
    { name: 'Sorrentinos orgánicos integrales de Verdura y Ricota "Dilaupé" (10 u)', amount: 0, url: '../images/shops/sorrentinosintegrales.jpg', type: 'meal', price: 180 },
    { name: 'Sorrentinos orgánicos integrales de Ricota, Ciboulette y Nuez "Dilaupé" (10 u)', amount: 0, url: '../images/shops/sorrentinosintegrales.jpg', type: 'meal', price: 180 },
    { name: 'Fideos orgánicos integrales de Zanahoria "Dilaupé" (1/4kg)', amount: 0, url: '../images/shops/fideointegralcolor.jpg', type: 'meal', price: 110 },
    { name: 'Fideos orgánicos integrales de Remolacha "Dilaupé" (1/4kg)', amount: 0, url: '../images/shops/fideointegralcolor.jpg', type: 'meal', price: 110 },
    { name: 'Fideos orgánicos integrales de Morrón "Dilaupé" (1/4kg)', amount: 0, url: '../images/shops/fideointegralcolor.jpg', type: 'meal', price: 110 },
    { name: 'Fideos orgánicos integrales de Espinaca "Dilaupé" (1/4kg)', amount: 0, url: '../images/shops/fideointegralcolor.jpg', type: 'meal', price: 110 },
    { name: 'Fideos orgánicos integrales al huevo "Dilaupé" (1/4kg)', amount: 0, url: '../images/shops/fideointegralcolor.jpg', type: 'meal', price: 110 },
    { name: 'Tartita orgánica integral de Espinaca "Dilaupé" (1u)', amount: 0, url: '../images/shops/tartaespinaca.jpg', type: 'meal', price: 100 },
    { name: 'Tartita orgánica integral de Calabaza "Dilaupé" (1u)', amount: 0, url: '../images/shops/tartacalabaza.jpg', type: 'meal', price: 100 },
    { name: 'Tartita orgánica integral de Pollo "Dilaupé" (1u)', amount: 0, url: '../images/shops/tartapollo.jpg', type: 'meal', price: 100 },
    { name: 'Tartita orgánica integral de Puerro "Dilaupé" (1u)', amount: 0, url: '../images/shops/tartapuerro.jpg', type: 'meal', price: 100 },
    { name: 'Tartita orgánica integral de Humita "Dilaupé" (1u)', amount: 0, url: '../images/shops/tartahumita.jpg', type: 'meal', price: 100 },
    { name: 'Granola (250g)', amount: 0, url: '../images/shops/granola.jpg', type: 'meal', price: 75 },
    { name: 'Hamburguesas veganas de lenteja y berenjena (x3)', amount: 0, url: '../images/shops/hamburguesaquinoa.jpg', type: 'meal', price: 100 },
    { name: 'Hamburguesas veganas de porotos adzuki y quinoa (x3)', amount: 0, url: '../images/shops/hamburguesaquinoa.jpg', type: 'meal', price: 100 },
    { name: 'Hamburguesas veganas de yamani y mix de veg (x3)', amount: 0, url: '../images/shops/hamburguesaquinoa.jpg', type: 'meal', price: 100 },
    { name: 'Falafels de Garbanzos (x3)', amount: 0, url: '../images/shops/falafelgarbanzo.jpg', type: 'meal', price: 100 },
    { name: 'Helado banana y mango vegano (200cc)', amount: 0, url: '../images/shops/heladomangobananavegano.jpg', type: 'meal', price: 60 },
    { name: 'Huevos (x12)', amount: 0, url: '../images/shops/huevos.jpg', type: 'meal', price: 120 },
    { name: 'Maple Huevos (x30)', amount: 0, url: '../images/shops/huevos.jpg', type: 'meal', price: 250 },
    { name: 'Huevos (x6)', amount: 0, url: '../images/shops/huevos.jpg', type: 'meal', price: 60 },
    { name: 'Mermelada de ciruela (400cc)', amount: 0, url: '../images/shops/mermelada.jpg', type: 'meal', price: 120 },
    { name: 'Miel Pura del delta (1Kg)', amount: 0, url: '../images/shops/mielkg.jpeg', type: 'meal', price: 270 },
    { name: 'Miel Pura del delta (1/2Kg)', amount: 0, url: '../images/shops/mielmedio.jpeg', type: 'meal', price: 150 },
    { name: 'Mermelada de ciruela (400cc)', amount: 0, url: '../images/shops/mermelada.jpg', type: 'meal', price: 120 },
    { name: 'Milanesas de berenjenas (500g)', amount: 0, url: '../images/shops/milanesaberenjena.jpg', type: 'meal', price: 100 },
    { name: 'Morrones verdes en almibar (830g)', amount: 0, url: '../images/shops/morronalmibar2.jpeg', type: 'meal', price: 100 },
    { name: 'Pastel de Batata y Lentejas (700g)', amount: 0, url: '../images/shops/pastelbatata.jpg', type: 'meal', price: 150 },
    { name: 'Tarta de calabaza y berenjena', amount: 0, url: '../images/shops/tartavariedad.jpg', type: 'meal', price: 110 },
    { name: 'Tarta de zapallito y puerro', amount: 0, url: '../images/shops/tartavariedad.jpg', type: 'meal', price: 110 },
    { name: 'Souflé. Mix de Vegetales con masa de calabaza ', amount: 0, url: '../images/shops/soufle.jpg', type: 'meal', price: 100 },
    { name: 'Tortilla vegana', amount: 0, url: '../images/shops/tortillavegana.jpg', type: 'meal', price: 90 },
    { name: 'Aceit Verdes "Simone" (100g)', amount: 0, url: '../images/shops/aceitunaverdekilo.jpeg', type: 'meal', price: 40 },
    { name: 'Aceit Verdes "Simone" (1Kg)', amount: 0, url: '../images/shops/aceitunaverdekilo.jpeg', type: 'meal', price: 350 },
    { name: 'Aceit Negras "Simone" (100g)', amount: 0, url: '../images/shops/aceitunanegrakilo.jpeg', type: 'meal', price: 40 },
    { name: 'Aceit Negras "Simone" (1Kg)', amount: 0, url: '../images/shops/aceitunanegrakilo.jpeg', type: 'meal', price: 350 },
    { name: 'Aceit Griegas "Simone" (100g)', amount: 0, url: '../images/shops/aceitunagriegakilo.jpeg', type: 'meal', price: 40 },
    { name: 'Aceit Griegas "Simone" (1Kg)', amount: 0, url: '../images/shops/aceitunagriegakilo.jpeg', type: 'meal', price: 350 },
    { name: 'Aceite de Oliva "Simone" (1L)', amount: 0, url: '../images/shops/aceiteoliva.jpeg', type: 'meal', price: 500 },
    { name: 'Barrita de cereal vegana x3', amount: 0, url: '../images/shops/barritacereal.jpg', type: 'meal', price: 100 },
]
products = products.sort()




