let products = [ 
    { name: 'Acelga (PAQ)', amount: 0, url: 'images/acelga.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Achicoria (10kg)', amount: 0, url: 'images/achicoria.jpg', type: 'veggie' },
    // { name: 'Cajón Aji Vinagre (10kg)', amount: 0, url: 'images/ajivinagre.jpg', type: 'veggie' },
    // { name: 'Ajo (x3)', amount: 0, url: 'images/ajo.jpg', type: 'veggie' },
    // { name: 'Cajón Albahaca (10u)', amount: 0, url: 'images/albahaca.jpg', type: 'veggie' },
    { name: 'Anco (kg)', amount: 0, url: 'images/anco.jpg', type: 'veggie', price: 40 },
    { name: 'Apio (Paq)', amount: 0, url: 'images/apio.jpg', type: 'veggie', price: 45 },
    { name: 'Banana (kg)', amount: 0, url: 'images/banana.jpeg', type: 'fruit', price: 30 },
    // { name: 'Bolsa Batata (17kg)', amount: 0, url: 'images/batata.jpg', type: 'veggie', price: 460 },
    // { name: 'Boniato (kg)', amount: 0, url: 'images/boniato.jpg', type: 'veggie', price: 350 },
    { name: 'Brócoli (PAQ)', amount: 0, url: 'images/brocoli.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Berenjena (10kg)', amount: 0, url: 'images/berenjena.jpg', type: 'veggie', price: 300 },
    { name: 'Caboutie (kg)', amount: 0, url: 'images/caboutie.jpg', type: 'veggie', price: 40 },
    // { name: 'Bolsa Cebolla (17kg)', amount: 0, url: 'images/cebolla.jpg', type: 'veggie', price: 600 },
    // { name: 'Bolsa Cebolla Morada (17kg)', amount: 0, url: 'images/cebollamorada.jpg', type: 'veggie', price: 700 },
    // { name: 'Cajón Chaucha (10kg)', amount: 0, url: 'images/chaucha.jpg', type: 'veggie', price: 300 },
    { name: 'Cilantro (PAQ)', amount: 0, url: 'images/cilantro.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Ciruela (kg)', amount: 0, url: 'images/ciruela.jpg', type: 'fruit', price: 70 },   
    // { name: 'Cajón Choclo (20u)', amount: 0, url: 'images/choclo.jpg', type: 'veggie' },
    { name: 'Coliflor (UNI)', amount: 0, url: 'images/coliflor.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Durazno (8kg)', amount: 0, url: 'images/durazno.jpg', type: 'fruit', price: 70 },
    { name: 'Espinaca (PAQ)', amount: 0, url: 'images/espinaca.jpg', type: 'veggie', price: 30 },
    { name: 'Hinojo (PAQ)', amount: 0, url: 'images/hinojo.jpg', type: 'veggie', price: 30 },   
    { name: 'Kale Morado (PAQ)', amount: 0, url: 'images/kalemorado.jpg', type: 'veggie', price: 30 },
    { name: 'Kale (PAQ)', amount: 0, url: 'images/kale.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Kiwi (8kg)', amount: 0, url: 'images/kiwi.jpg', type: 'fruit', price: 600 },
    { name: 'Lechuga (kg)', amount: 0, url: 'images/lechugacrespa.jpg', type: 'veggie', price: 30 },
    { name: 'Limon (kg)', amount: 0, url: 'images/limon.jpg', type: 'fruit', price: 30 },
    // { name: 'Cajón Melon (8kg)', amount: 0, url: 'images/melon.jpg', type: 'fruit', price:  },
    // { name: 'Cajón Mango (8kg)', amount: 0, url: 'images/mango.jpg', type: 'fruit', price:  },
    { name: 'Manzana Roja (kg)', amount: 0, url: 'images/manzana.jpg', type: 'fruit', price: 25 },
    // { name: 'Cajón Manzana Verde (18kg)', amount: 0, url: 'images/manzanaverde.jpg', type: 'fruit', price: 750 },
    { name: 'Mandarina (kg)', amount: 0, url: 'images/mandarina.jpg', type: 'fruit', price: 40 },
    // { name: 'Cajón Maracuya (8kg)', amount: 0, url: 'images/maracuya.jpg', type: 'fruit', price: 1000 },
    // { name: 'Cajón Morron Verde (10kg)', amount: 0, url: 'images/morron.jpg', type: 'veggie', price: 300 },
    // { name: 'Cajón Morron Rojo (10kg)', amount: 0, url: 'images/morronrojo.jpg', type: 'veggie', price: 300 },
    // { name: 'Cajón Nabo (10 Paq)', amount: 0, url: 'images/nabo.jpg', type: 'veggie', price: 300 },
    { name: 'Naranja (kg)', amount: 0, url: 'images/naranja.jpg', type: 'fruit', price: 40 },
    // { name: 'Pack Choi (Paq)', amount: 0, url: 'images/packchoi.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Palta (10kg)', amount: 0, url: 'images/palta.jpg', type: 'fruit', price: 1000 },
    // { name: 'Papa (kg)', amount: 0, url: 'images/papa.jpg', type: 'veggie', price: 25 },
    // { name: 'Bolsa Papa Colorada (17kg)', amount: 0, url: 'images/papacolorada.jpg', type: 'veggie', price: 400 },
    { name: 'Pomelo Rosado (kg)', amount: 0, url: 'images/pomelo.jpg', type: 'fruit', price: 40 },  
    // { name: 'Cajón Pepino (10kg)', amount: 0, url: 'images/pepino.jpg', type: 'veggie', price: 300 },
    { name: 'Pera (kg)', amount: 0, url: 'images/pera.jpeg', type: 'fruit', price: 40 },
    { name: 'Perejil (kg)', amount: 0, url: 'images/perejil.jpg', type: 'veggie', price: 30 },
    { name: 'Puerro (PAQ)', amount: 0, url: 'images/puerro.jpg', type: 'veggie', price: 30 },
    { name: 'Rabanito (PAQ)', amount: 0, url: 'images/rabanito.jpg', type: 'veggie', price: 30 },
    { name: 'Radicheta (PAQ)', amount: 0, url: 'images/radicheta.jpg', type: 'veggie', price: 30 },
    { name: 'Repollo (kg)', amount: 0, url: 'images/repollo.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Repollito de Brusela (10kg)', amount: 0, url: 'images/repollitobrusela.jpg', type: 'veggie', price: 1000 },
    { name: 'Remolacha (PAQ)', amount: 0, url: 'images/remolacha.jpg', type: 'veggie', price: 30 },
    { name: 'Rúcula (Paq)', amount: 0, url: 'images/rucula.jpg', type: 'veggie', price: 25 },
    // { name: 'Sandia (kg)', amount: 0, url: 'images/watermelon.jpg', type: 'fruit', price:  },
    { name: 'Tomate (kg)', amount: 0, url: 'images/tomate.jpg', type: 'veggie', price: 40 },
    // { name: 'Bolsa Toronja (uni)', amount: 0, url: 'images/toronja.jpg', type: 'fruit', price:  },
    // { name: 'Cajón Tomate Cherry (5kg)', amount: 0, url: 'images/tomatecherry.jpg', type: 'veggie', price: 300 },
    // { name: 'Cajón Uva (8kg)', amount: 0, url: 'images/uva.jpg', type: 'fruit', price: },
    { name: 'Verdeo (PAQ)', amount: 0, url: 'images/verdeo.jpg', type: 'veggie', price: 30 },
    { name: 'Zanahoria (PAQ)', amount: 0, url: 'images/zanahoria.jpg', type: 'veggie', price: 30 },
    // { name: 'Cajón Zapallito (10kg)', amount: 0, url: 'images/zapallitos.jpg', type: 'veggie' },
    // { name: 'Cajón Zuchinni (10kg)', amount: 0, url: 'images/zuchinni.jpg', type: 'veggie' },
    { name: 'Arroz Yamaní Org Integral NOVEDAD SUMATE! (3KG)', amount: 0, url: 'images/arrozyamani.jpg', type: 'meal', price: 300 },
    // { name: 'Jengibre (100g)', amount: 0, url: 'images/jengibre.jpg', type: 'meal', price: 30 },
    // { name: 'Cúrcuma (100g)', amount: 0, url: 'images/curcuma.jpeg', type: 'meal', price: 30 },
    { name: 'Champiñon (250g)', amount: 0, url: 'images/champi.jpg', type: 'meal', price: 110 },
    { name: 'Portobello (250g)', amount: 0, url: 'images/portobello.jpg', type: 'meal', price: 110 },
    // { name: 'Shitake (250g)', amount: 0, url: 'images/shitake.jpg', type: 'meal', price: 135 },
    { name: 'Gírgolas (250g)', amount: 0, url: 'images/girgolas.jpg', type: 'meal', price: 135 },
    // { name: 'Bolsa Nueces de Catamarca (5kg)', amount: 0, url: 'images/nueces.jpg', type: 'meal', price: 1400 },
    // { name: 'Caja Vino Biodinámico x 750ml (6u)', amount: 0, url: 'images/vino.jpg', type: 'meal', price: 780 },
    { name: 'Arvejas (kg)', amount: 0, url: 'images/arveja.jpg', type: 'meal', price: 60 },
    { name: 'Garbanzos (kg)', amount: 0, url: 'images/garbanzo.jpg', type: 'meal', price: 75 },
    { name: 'Maiz Pisingallo (kg)', amount: 0, url: 'images/maizpisingallo.jpg', type: 'meal', price: 60 },
    { name: 'Lino Dorado (kg)', amount: 0, url: 'images/linodorado.jpg', type: 'meal', price: 70 },
    { name: 'Lino Marrón (kg)', amount: 0, url: 'images/linomarron.jpg', type: 'meal', price: 70 },
    { name: 'Sésamo (kg)', amount: 0, url: 'images/sesamo.jpg', type: 'meal', price: 190 },
    { name: 'Chía (kg)', amount: 0, url: 'images/chia.jpg', type: 'meal', price: 190 },
    { name: 'Mijo (kg)', amount: 0, url: 'images/mijo.jpg', type: 'meal', price: 105 },
    { name: 'Lentejas (kg)', amount: 0, url: 'images/lenteja.jpg', type: 'meal', price: 85 },
    { name: 'Poroto Adzuki (kg)', amount: 0, url: 'images/porotoadzuki.jpg', type: 'meal', price: 85 },
    { name: 'Poroto Mung (kg)', amount: 0, url: 'images/porotomung.jpg', type: 'meal', price: 95 },
    { name: 'Porotos Soja (kg)', amount: 0, url: 'images/soja.jpg', type: 'meal', price: 50 },
    { name: 'Trigo candeal (kg)', amount: 0, url: 'images/trigo.jpg', type: 'meal', price: 35 },
    { name: 'Poroto Colorado (kg)', amount: 0, url: 'images/porotocolorado.jpg', type: 'meal', price: 85 },
    { name: 'Poroto Negro (kg)', amount: 0, url: 'images/porotonegro.jpg', type: 'meal', price: 85 },
    { name: 'Bolsa Avena arrollada (kg)', amount: 0, url: 'images/avena.jpg', type: 'meal', price: 100 },
    { name: 'Paq. Polenta "Del Campo" x 500g  (5u)', amount: 0, url: 'images/polenta.jpg', type: 'meal', price: 150 },
    { name: 'Azucar "Schatzi" (3kg)', amount: 0, url: 'images/azucar.jpg', type: 'meal', price: 270 },
    { name: 'Arroz Yamaní Integral "Schatzi" (3kg)', amount: 0, url: 'images/arrozyamani.jpg', type: 'meal', price: 320 },
    { name: 'Arroz Blanco "Schatzi" (3kg)', amount: 0, url: 'images/arrozlargointegral.jpg', type: 'meal', price: 340 },
    { name: 'Granola "Schatzi" (1,5kg)', amount: 0, url: 'images/granolaintegral.jpg', type: 'meal', price: 325 },
    { name: 'Proteina de Soja "Schatzi" (1,5kg)', amount: 0, url: 'images/proteinadesoja.jpg', type: 'meal', price: 210 },
    // { name: 'Azucar rubia orgánica "Schatzi" (500g)', amount: 0, url: 'images/azucarrubia.jpg', type: 'meal', price: 65 },
    // { name: 'Queso crema "La Choza" (175grs)', amount: 0, url: 'images/quesocrema175.jpg', type: 'meal', price: 85 },
    // { name: 'Yogurt Natural descremado "La Choza" (1Lt)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 160 },
    // { name: 'Yogurt Entero de Mora "La Choza" (1Lt)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 200 },
    // { name: 'Yogurt Descremado de Frutos Rojos "La Choza" (1Lt)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 200 },
    // { name: 'Yogurt Natural Descremado "La Choza" (175g)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 50 },
    // { name: 'Yogurt Entero de Vainilla "La Choza" (175g)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 60 },
    // { name: 'Yogurt Entero de Mora "La Choza" (175g)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 60 },
    // { name: 'Yogurt Entero de Frutilla "La Choza" (175g)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 60 },
    // { name: 'Yogurt Descremado de Frutos del Bosque "La Choza" (175g)', amount: 0, url: 'images/yogurtchoza.jpg', type: 'meal', price: 60 },
    { name: 'Maple Huevos (x30)', amount: 0, url: 'images/huevos.jpg', type: 'meal', price: 180 },
    { name: 'Miel Pura x Kg', amount: 0, url: 'images/mielkg.jpeg', type: 'meal', price: 150 },
    { name: 'Miel Pura x 1/2Kg', amount: 0, url: 'images/mielmedio.jpeg', type: 'meal', price: 90 },
    // { name: 'Aceit Verdes "Simone" (100g)', amount: 0, url: 'images/aceitunaverdekilo.jpeg', type: 'meal', price: 40 },
    { name: 'Aceit Verdes "Simone" (1Kg)', amount: 0, url: 'images/aceitunaverdekilo.jpeg', type: 'meal', price: 300 },
    // { name: 'Aceit Negras "Simone" (100g)', amount: 0, url: 'images/aceitunanegrakilo.jpeg', type: 'meal', price: 40 },
    { name: 'Aceit Negras "Simone" (1Kg)', amount: 0, url: 'images/aceitunanegrakilo.jpeg', type: 'meal', price: 300 },
    // { name: 'Aceit Griegas "Simone" (100g)', amount: 0, url: 'images/aceitunagriegakilo.jpeg', type: 'meal', price: 40 },
    { name: 'Aceit Griegas "Simone" (1Kg)', amount: 0, url: 'images/aceitunagriegakilo.jpeg', type: 'meal', price: 300 },
    // { name: 'Aceite de Oliva "Simone" (1L)', amount: 0, url: 'images/aceiteoliva.jpg', type: 'meal', price: 450 },
    
]
products = products.sort()

let discounts = [
    { amount: "1", price: 55 },
    { amount: "2", price: 52.50 },
    { amount: "3", price: 50 },
    { amount: "4", price: 47.50 },
    { amount: "5+", price: 45 },
    //{ amount: "60 > 200", price: 41 },
    //{ amount: "200 > 250", price: 36 },
    //{ amount: "250 >", price: 32 }
]


//Scroll top on pageload
window.addEventListener('scroll', function (evt) {

    var distance_from_top = document.documentElement.scrollTop

    if (distance_from_top === 0) {
        document.getElementsByClassName("search")[0].classList.remove("fixed");
    }
k
    if (distance_from_top > 0) {
        document.getElementsByClassName("search")[0].classList.add("fixed");
    }

});